name: 'CustomSkinsManager'
main: 'ru.csm.bukkit.SpigotSkinsManager'
version: '3.4'
api-version: '1.13'
author: '_Nanit_'
softdepend:
  - "PlaceholderAPI"
commands:
  csm:
    description: 'Custom Skins Manager main command'
    aliases: ["skin", "skins"]
    permission-message: "You don't have permission to do that"
  csmskull:
    permission: 'csm.skulls'
    description: 'Custom Skins Manager skull command'
    aliases: ["skull"]
    permission-message: "You don't have permission to do that"
permissions:
  csm.skin.player:
    description: "Allow to setup skin from license name"
  csm.skin.url:
    description: "Allow to setup skin from url to image"
  csm.skin.menu:
    description: "Allow to open menu with users skins"
  csm.skin.reset:
    description: "Allow to reset skin to default"
  csm.skin.to:
    description: "Allow to setup skins for any player"
  csm.skin.preview:
    description: "Allow to show skin preview via NPC"
  csm.skull.player:
    description: "/skull player command"
  csm.skull.url:
    description: "/skull url command"
  csm.skull.to:
    description: "/skull to command"